#spring:
#  datasource:
#    url: jdbc:h2:mem:businessmanagement
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#mybatis:
#  mapper-locations: classpath*:mapper/*.xml
#  type-aliases-package: com.example.businessmanagement2.repository.user.**
#  configuration:
#    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:h2:mem:businessmanagement
    driverClassName: org.h2.Driver
    username: sa
    password:

#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#    local-cache-scope: statement
#  lazy-initialization: false
##  type-handlers-package: com.example.springmybatis.da.typehandler
#
#logging:
#  level:
#    com.example.businessmanagement2.repository.user: debug
#
